In [ ]:
import os as os
import pandas as pd
import tensorflow as tf
import numpy as np

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Cybertrolling_Project/Data/train/train.csv")


In [ ]:
df.size

1276568

In [ ]:
 df.head()


id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [ ]:
df.tail()

id                                       comment_text  \
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
159568  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
159566      0             0        0       0       0              0  
159567      0             0        0       0       0              0  
159568      0             0        0       0       0              0  
159569      0             0        0       0       0              0  
159570      0             0        0       0       0              0

In [ ]:
df.iloc[4]['comment_text']

"You, sir, are my hero. Any chance you remember what page that's on?"

In [ ]:
df[df.columns[2:]].iloc[3]

toxic            0
severe_toxic     0
obscene          0
threat           0
insult           0
identity_hate    0
Name: 3, dtype: int64

In [ ]:
from tensorflow.keras.layers import TextVectorization

In [ ]:
!pip list

Package                      Version
---------------------------- ---------
absl-py                      1.2.0
asttokens                    2.0.7
astunparse                   1.6.3
backcall                     0.2.0
cachetools                   5.2.0
certifi                      2022.6.15
charset-normalizer           2.1.0
colorama                     0.4.5
cycler                       0.11.0
debugpy                      1.6.2
decorator                    5.1.1
entrypoints                  0.4
executing                    0.9.1
flatbuffers                  1.12
fonttools                    4.34.4
gast                         0.4.0
google-auth                  2.10.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
grpcio                       1.47.0
h5py                         3.7.0
idna                         3.3
ipykernel                    6.15.1
ipython                      8.4.0
jedi                         0.18.1
joblib                       1.1.0
jupyter-c

You should consider upgrading via the 'C:\Users\sbbar\Desktop\NLP_Project1\env\Scripts\python.exe -m pip install --upgrade pip' command.


In [ ]:
X = df['comment_text']
y = df[df.columns[2:]].values

In [ ]:
MAX_FEATURES = 200000

In [ ]:
vectorizer = TextVectorization(max_tokens=MAX_FEATURES,output_sequence_length=1800,
                                output_mode='int')

In [ ]:
vectorizer.adapt(X.values)

In [ ]:
vectorizer('Hello world , life is beautiful')[:5]

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([ 286,  261,  305,    9, 3003], dtype=int64)>

In [ ]:
vectorized_text = vectorizer(X.values)

In [ ]:
vectorized_text

<tf.Tensor: shape=(159571, 1800), dtype=int64, numpy=
array([[  643,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2506, ...,     0,     0,     0],
       [  425,   440,    70, ...,     0,     0,     0],
       ...,
       [32141,  7329,   383, ...,     0,     0,     0],
       [    5,    12,   533, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]], dtype=int64)>

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text,y))
dataset = dataset.cache()
dataset = dataset.shuffle(160000)
dataset = dataset.batch(16)
dataset = dataset.prefetch(8)

In [ ]:
batch_X,batch_y = dataset.as_numpy_iterator().next()

In [ ]:
len(dataset) # not actual size this is batch size

9974

In [ ]:
train = dataset.take(int(len(dataset)*.7))
val = dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.2))
test = dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.1)) 

In [ ]:
train_generator = train.as_numpy_iterator()

In [ ]:
train_generator.next()

(array([[  856,  1057,   178, ...,     0,     0,     0],
        [27823,  1278,     2, ...,     0,     0,     0],
        [   47,    97,  2975, ...,     0,     0,     0],
        ...,
        [   36,   122,    70, ...,     0,     0,     0],
        [   11,   552,    27, ...,     0,     0,     0],
        [    8,   252,    10, ...,     0,     0,     0]], dtype=int64),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 1, 1, 0, 1, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]], dtype=int64))

## Creating Sequential Model 

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dropout,Bidirectional,Dense,Embedding

In [ ]:
model = Sequential()

model.add(Embedding(MAX_FEATURES+1,32))
model.add(Bidirectional(LSTM(32,activation='tanh')))
model.add(Dense(128,activation='relu'))
model.add(Dense(256,activation='relu'))
model.add(Dense(128,activation='relu'))

model.add(Dense(6,activation='sigmoid'))




In [ ]:
model.compile(loss='BinaryCrossentropy',optimizer='Adam')

In [ ]:
model.summary()

In [ ]:
history = model.fit(train,epochs=1,validation_data=val)

6981/6981 [==============================] - 7217s 1s/step - loss: 0.0629 - val_loss: 0.0478


## Make Predictions

In [ ]:
batch = test.as_numpy_iterator().next()


In [ ]:
input_text = vectorizer('You freaking sucks')


In [ ]:
model.predict(np.expand_dims(input_text,0))

1/1 [==============================] - 2s 2s/step


array([[0.99042344, 0.21359184, 0.9348599 , 0.06115354, 0.80646306,
        0.196076  ]], dtype=float32)

In [ ]:
res = model.predict(np.expand_dims(input_text,0))

In [ ]:
from tensorflow.keras.metrics import Precision,Recall,CategoricalAccuracy

In [ ]:
pre = Precision()
re = Recall()
acc = CategoricalAccuracy()

In [ ]:
for batch in test.as_numpy_iterator():
    X_true,y_true = batch
    yhat = model.predict(X_true)

    y_true = y_true.flatten()
    yhat = yhat.flatten()

    pre.update_state(y_true,yhat)
    re.update_state(y_true,yhat)
    acc.update_state(y_true,yhat)

1/1 [==============================] - 0s 256ms/step


In [ ]:
print(f'Precision:{pre.result().numpy()}, Recall:{pre.result().numpy()},Accuracy:{acc.result().numpy()}')

Precision:0.859622061252594, Recall:0.859622061252594,Accuracy:0.48445335030555725


In [ ]:
import gradio as gr

In [ ]:
model.save('toxicity.h5')

In [ ]:
model = tf.keras.models.load_model('toxicity.h5')

In [ ]:
df.columns[2:]

Index(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='object')

In [ ]:
res

array([[0.9365812 , 0.0413784 , 0.7380093 , 0.03913265, 0.5753122 ,
        0.11249049]], dtype=float32)

In [ ]:
def score_comment(comment):
    vectorized_comment = vectorizer([comment])
    results = model.predict(vectorized_comment)
    
    text = ''
    for idx, col in enumerate(df.columns[2:]):
        text += '{}: {}\n'.format(col, results[0][idx]>0.5)
    
    return text

In [ ]:
interface = gr.Interface(fn=score_comment, 
                         inputs=gr.inputs.Textbox(lines=2, placeholder='Comment to score'),
                        outputs='text')

c:\Users\sbbar\Desktop\NLP_Project1\env\lib\site-packages\gradio\inputs.py:26: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
c:\Users\sbbar\Desktop\NLP_Project1\env\lib\site-packages\gradio\deprecation.py:40: UserWarning: `optional` parameter is deprecated, and it has no effect
  warnings.warn(value)
c:\Users\sbbar\Desktop\NLP_Project1\env\lib\site-packages\gradio\deprecation.py:40: UserWarning: `numeric` parameter is deprecated, and it has no effect
  warnings.warn(value)
c:\Users\sbbar\Desktop\NLP_Project1\env\lib\site-packages\gradio\deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)


In [ ]:
interface.launch(share=True)

Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://13763.gradio.app

This share link expires in 72 hours. For free permanent hosting, check out Spaces: https://huggingface.co/spaces


(<gradio.routes.App at 0x1441fcab9a0>,
 'http://127.0.0.1:7860/',
 'https://13763.gradio.app')

Traceback (most recent call last):
  File "c:\Users\sbbar\Desktop\NLP_Project1\env\lib\site-packages\gradio\routes.py", line 255, in run_predict
    output = await app.blocks.process_api(
  File "c:\Users\sbbar\Desktop\NLP_Project1\env\lib\site-packages\gradio\blocks.py", line 630, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "c:\Users\sbbar\Desktop\NLP_Project1\env\lib\site-packages\gradio\blocks.py", line 545, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "c:\Users\sbbar\Desktop\NLP_Project1\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "c:\Users\sbbar\Desktop\NLP_Project1\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "c:\Users\sbbar\Desktop\NLP_Project1\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.r